# Generated by Django 6.0.3 on 2026-03-30 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('client_nom', models.CharField(max_length=150)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_telephone', models.CharField(blank=True, max_length=20)),
                ('client_adresse', models.TextField(blank=True)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('en_attente', 'En attente'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=0, help_text='Taux TVA en %', max_digits=5)),
                ('montant_tva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'db_table': 'factures',
                'ordering': ['-date_emission', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'db_table': 'lignes_facture',
            },
        ),
    ]
